version: '3.7'

services:

  deckbuilder_app:
    container_name: deckbuilder_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'